---
apiVersion: organizations.github.crossplane.io/v1alpha1
kind: Team
metadata:
  name: sample-team
spec:
  forProvider:
    description: This is a sample team
    orgRef: 
      name: pgh-sample-organization
    members:
    - userRef:
        name: pgh-sample-user
      role: maintainer # Note: If the user is an ORG admin, make sure to set it to "maintainer". GitHub enforces that ORG admins can only be maintainers in teams
    privacy: closed
---
apiVersion: organizations.github.crossplane.io/v1alpha1
kind: Team
metadata:
  name: sample-sub-team
spec:
  forProvider:
    description: This is a sample team with a parent
    parentRef:
      name: sample-team
    orgRef: 
      name: pgh-sample-organization
    members:
    - userRef:
        name: pgh-sample-user
      role: maintainer # Note: If the user is an ORG admin, make sure to set it to "maintainer". GitHub enforces that ORG admins can only be maintainers in teams
    privacy: closed
